
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class TaxCalc extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        //read the request
        String s1 = req.getParameter("t1");         //Income
        String s2 = req.getParameter("t2");         //Age
        String s3 = req.getParameter("t3");         //Password
        String s4 = req.getParameter("t4");         //City    
        String s5[] = req.getParameterValues("t5"); //Assets
        String res = "";
        if (s5 != null) {
            for (String tmp : s5) {
                res = res + tmp + ",";
            }
        } else {
            res = "No Assets Is Declared By You";
        }

        String s6 = req.getParameter("t6");         //Hidden

        //process the request
        int tax = 0, rebate = 0, netTax = 0;
        int income = Integer.parseInt(s1);
        int age = Integer.parseInt(s2);

        if (income >= 500000) {
            tax = income * 20 / 100;
        } else {
            tax = income * 10 / 100;
        }

        if (age >= 60) {
            rebate = tax * 10 / 100;
        }
        netTax = tax - rebate;

        //provide the response
        try (PrintWriter out = resp.getWriter()) {

            out.println("<html>");
            out.println("<body bgcolor=\"Orange\">");
            out.println("<h2>Tax Details</h2>");

            out.println("<h3>Your Pin : " + s3 + "</h3>");
            out.println("<h3>Your City : " + s4 + "</h3>");
            out.println("<h3>Your Assets : " + res + "</h3>");
            out.println("<h3>Hidden Code : " + s6 + "</h3>");

            out.println("<table border=\"1\" align=center>");

            out.println("<tr>");
            out.println("<td>Income</td>");
            out.println("<td>" + income + "</td>");
            out.println("</tr>");

            out.println("<tr>");
            out.println("<td>Age</td>");
            out.println("<td>" + age + "</td>");
            out.println("</tr>");

            out.println("<tr>");
            out.println("<td>Tax</td>");
            out.println("<td>" + tax + "</td>");
            out.println("</tr>");

            out.println("<tr>");
            out.println("<td>Rebate</td>");
            out.println("<td>" + rebate + "</td>");
            out.println("</tr>");

            out.println("<tr>");
            out.println("<td>NetTax</td>");
            out.println("<td>" + netTax + "</td>");
            out.println("</tr>");

            out.println("</table>");
            out.println("<br>");
            out.println("<hr>");
            out.println("<p align=center>This Page Is Generated By Servlet...</p>");
            out.println("<hr>");
            out.println("<marquee style=\"color : blue\"><strong>Pay Your Taxes Before 31st March</strong></marquee>");
            out.println("</body>");
            out.println("</html>");
        }
    }
}
